package com.hashedin.csvapi.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "Movie")
public class Movie {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String title;
    @DynamoDBAttribute
    private String date_published;
    @DynamoDBAttribute
    private String genre;
    @DynamoDBAttribute
    private String duration;
    @DynamoDBAttribute
    private String country;
    @DynamoDBAttribute
    private String movie_language;
    @DynamoDBAttribute
    private String director;

    @DynamoDBAttribute
    private Integer budget;

    @DynamoDBAttribute
    private Integer reviews_from_users;


    public Movie(String title, String date_published, String genre, String duration, String country, String movie_language, String director
    , Integer reviews_from_users, Integer budget) {
        this.title = title;
        this.date_published = date_published;
        this.genre=genre;
        this.duration = duration;
        this.country = country;
        this.movie_language = movie_language;
        this.director = director;
        this.budget = budget;
        this.reviews_from_users = reviews_from_users;
    }
}
